server:
  port: 8181

spring:
  profiles.include: login
  datasource:
    url: jdbc:mysql://localhost:3306/switdb
    username: swit
    password: swit1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  servlet:
    multipart: 
      max-request-size: 30MB
      max-file-size: 20MB  


com:
    swit:
        upload:
            path: upload
jwt:
  secret: your-secret-key